/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Archivo;
import Clases.ClaseGeneral;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Erick Contreras
 */
public class ModificacionDatos extends javax.swing.JFrame {

    /**
     * Creates new form ModificacionDatos
     */
    public ModificacionDatos() {
        initComponents();
        jUsuario.setText(ClaseGeneral.usuarioActual);
        buscarUsuario(ClaseGeneral.usuarioActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtnVolver = new javax.swing.JButton();
        jBtnPassword = new javax.swing.JButton();
        jBtnCorreo = new javax.swing.JButton();
        jBtnFecha = new javax.swing.JButton();
        jBtnTelefono = new javax.swing.JButton();
        jBtnFoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGO_MEIA2 p.png"))); // NOI18N

        jUsuario.setText("jLabel2");

        jLabel2.setText("Que desea modificar?");

        jBtnVolver.setText("Volver");
        jBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolverActionPerformed(evt);
            }
        });

        jBtnPassword.setText("Contraseña");
        jBtnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPasswordActionPerformed(evt);
            }
        });

        jBtnCorreo.setText("Correo");
        jBtnCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCorreoActionPerformed(evt);
            }
        });

        jBtnFecha.setText("Fecha de nacimiento");
        jBtnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFechaActionPerformed(evt);
            }
        });

        jBtnTelefono.setText("Teléfono");
        jBtnTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTelefonoActionPerformed(evt);
            }
        });

        jBtnFoto.setText("Fotografía");
        jBtnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUsuario)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jBtnVolver)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jBtnFecha)
                            .addGap(133, 133, 133)))
                    .addComponent(jBtnTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(25, 25, 25)
                .addComponent(jBtnPassword)
                .addGap(18, 18, 18)
                .addComponent(jBtnCorreo)
                .addGap(18, 18, 18)
                .addComponent(jBtnFecha)
                .addGap(18, 18, 18)
                .addComponent(jBtnTelefono)
                .addGap(18, 18, 18)
                .addComponent(jBtnFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jBtnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolverActionPerformed
        // TODO add your handling code here:
        ClaseGeneral.busqueda = false;
        Mantenimiento mante = new Mantenimiento();
        mante.show();
        this.hide();
    }//GEN-LAST:event_jBtnVolverActionPerformed

    private void jBtnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFotoActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(null, "Desea modificar la foto?");
        if (opc == 0) {
            JFileChooser dialogo = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Foto de perfil", "jpg");
            File ficheroImagen;
            String rutaArchivo = "";
            dialogo.setFileFilter(filtro);
            int valor = dialogo.showOpenDialog(this);
            if (valor == JFileChooser.APPROVE_OPTION) {
                ficheroImagen = dialogo.getSelectedFile();
                rutaArchivo = ficheroImagen.getPath();
                ClaseGeneral.rutaFotografia = rutaArchivo;
            }
            modificarDatosBuscado("foto", rutaArchivo);
        }
    }//GEN-LAST:event_jBtnFotoActionPerformed

    private void jBtnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPasswordActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(null, "Desea modificar la contraseña?");
        if (opc == 0) {
            String cambio = JOptionPane.showInputDialog(rootPane, "Ingrese la nueva contraseña");
            modificarDatosBuscado("pass", cambio);
        }
    }//GEN-LAST:event_jBtnPasswordActionPerformed

    private void jBtnCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCorreoActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(null, "Desea modificar el correo?");
        if (opc == 0) {
            String cambio = JOptionPane.showInputDialog(rootPane, "Ingrese el nuevo correo");
            modificarDatosBuscado("correo", cambio);
        }
    }//GEN-LAST:event_jBtnCorreoActionPerformed

    private void jBtnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFechaActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(null, "Desea modificar su fecha de nacimiento?");
        if (opc == 0) {
            String cambio = JOptionPane.showInputDialog(rootPane, "Ingrese la nueva fecha en formato YYYY/MM/DD");
            //Validar el formato de la fecha
            SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy/MM/dd");
            String strFecha = cambio;
            Date fecha = null;
            try {

                fecha = formatoDelTexto.parse(strFecha);
                 modificarDatosBuscado("fecha", formatoDelTexto.format(fecha));

            } catch (ParseException ex) {

                JOptionPane.showMessageDialog(rootPane, "Ingrese nuevamente en este formato YYYY/MM/DD");
            }
           
        }
    }//GEN-LAST:event_jBtnFechaActionPerformed

    private void jBtnTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTelefonoActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(null, "Desea modificar su número de teléfono?");
        if (opc == 0) {
            String cambio = JOptionPane.showInputDialog(rootPane, "Ingrese el nuevo número");
            modificarDatosBuscado("tel", cambio);
        }
    }//GEN-LAST:event_jBtnTelefonoActionPerformed

    boolean encontrado = false;

    public void buscarUsuario(String usuario) {
        Archivo archivo = new Archivo();
        encontrado = false;
        String[] datos;
        //Lee la bitacora para hacer una busqueda en esta
        String[] usuarios = archivo.leerArchivo("bitacora");
        if (usuarios != null) {
            for (int i = 0; i < usuarios.length; i++) {
                if (usuarios[i] != null) {
                    datos = usuarios[i].split("\\|");
                    if (usuario.equals(datos[1])) {
                        encontrado = true;
                        ClaseGeneral.datosUsuarioBuscado = datos;
                        break;
                    }
                }
            }
        }

        //Si no lo encontro en la bitacora lee usuarios
        if (!encontrado) {
            usuarios = null;
            usuarios = archivo.leerArchivo("usuario");
            if (usuarios != null) {
                for (int i = 0; i < usuarios.length; i++) {
                    if (usuarios[i] != null) {
                        datos = usuarios[i].split("\\|");
                        if (usuario.equals(datos[1])) {
                            encontrado = true;
                            ClaseGeneral.datosUsuarioBuscado = datos;
                            break;
                        }
                    }
                }
            }
        }
    }

    public void modificarDatosBuscado(String tipo, String nuevo) {
        Archivo archivo = new Archivo();
        boolean estaEnBitacora = false;
        String[] datosUsuario = null, split = null, splitaux = null, cambiar = null;

        int posicion = 0;
        split = archivo.leerArchivo("bitacora");
        splitaux = split;
        for (int i = 0; i < split.length; i++) {
            if (split[i] != null) {
                datosUsuario = split[i].split("\\|");
                if (datosUsuario[0].equals(ClaseGeneral.datosUsuarioBuscado[0])) {
                    posicion = i;
                    estaEnBitacora = true;
                    splitaux[posicion] = "";
                } else {
                    splitaux[i] = split[i];
                }
            }
        }

        if (!estaEnBitacora) {
            split = null;
            splitaux = null;
            split = archivo.leerArchivo("usuario");
            splitaux = split;
            for (int i = 0; i < split.length; i++) {
                if (split[i] != null) {
                    datosUsuario = split[i].split("\\|");
                    if (datosUsuario[0].equals(ClaseGeneral.datosUsuarioBuscado[0])) {
                        posicion = i;
                        splitaux[posicion] = "";
                        cambiar = datosUsuario;
                    } else {
                        splitaux[i] = split[i];
                    }
                }
            }
        }
        if (tipo.equals("pass")) {
            cambiar[3] = nuevo;
        } else if (tipo.equals("foto")) {
            cambiar[8] = nuevo;
        } else if (tipo.equals("tel")) {
            cambiar[7] = nuevo;
        } else if (tipo.equals("correo")) {
            cambiar[6] = nuevo;
        } else if (tipo.equals("fecha")) {
            cambiar[5] = nuevo;
        }

        //Rearma la linea de los datos del usuario
        String cadena = "";
        for (int i = 0; i < cambiar.length; i++) {
            if (i == cambiar.length - 1) {
                cadena += cambiar[i];
                break;
            }
            cadena += cambiar[i] + "|";
        }

        String nombreEscribir = "";
        if (estaEnBitacora) {
            nombreEscribir = "bitacora";
        } else {
            nombreEscribir = "usuario";
        }
        splitaux[posicion] = cadena;

        //Rearma todo el contenido del split para escribirlo en el archivo
        archivo.limpiarArchivo(nombreEscribir);
        String error = "";
        cadena = "";
        for (int i = 0; i < splitaux.length; i++) {
            if (splitaux[i] != null) {
                archivo.escribirArchivo2(nombreEscribir, splitaux[i], error);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificacionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificacionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificacionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificacionDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificacionDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCorreo;
    private javax.swing.JButton jBtnFecha;
    private javax.swing.JButton jBtnFoto;
    private javax.swing.JButton jBtnPassword;
    private javax.swing.JButton jBtnTelefono;
    private javax.swing.JButton jBtnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jUsuario;
    // End of variables declaration//GEN-END:variables
}
